export const HANDLE_SET_PRODUCTS_TO_SHOW = 'HANDLE_SET_PRODUCTS_TO_SHOW'

export const HANDLE_SET_PRODUCTS_AMOUNT = 'HANDLE_SET_PRODUCTS_AMOUNT'

export const HANDLE_SET_REMAINING_PRODUCTS = 'HANDLE_SET_REMAINING_PRODUCTS'
